[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sayac_2 = "7paSjt3bwfUFibAcNf7rbqGDTN8XawvHXho2VyzQ4m35"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
